//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MingEventsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Armchair
    {
        public int armchair_id { get; set; }
        public int columns { get; set; }
        public int rows { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> establish_id { get; set; }
    }
}
