//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MingEventsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Establishment
    {
        public int establish_id { get; set; }
        public string name { get; set; }
        public string direction { get; set; }
        public int capacity { get; set; }
        public int city_id { get; set; }
    }
}
