//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MingEventsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserve_Ticket
    {
        public int armchair_id { get; set; }
        public int user_id { get; set; }
        public string reservation_date { get; set; }
    
        public virtual Armchair Armchair { get; set; }
        public virtual Users Users { get; set; }
    }
}
